### ISSUE TITLE
JavaScript is broken with linking directly to Zero-to-Deploy

### ISSUE THREAD

**Issue by marksiemers** [amberframework/amberframework.org#91]
Going directly here: https://amberframework.org/guides/getting-started/quick-start.md#zero-to-deploy

The JS is broken and none of the pages in the guide will load:
```
core.min.js:2 jQuery.Deferred exception: Cannot read property 'href' of null TypeError: Cannot read property 'href' of null
    at s (https://amberframework.org/dist/sidebar.bundle.js:2:46007)
    at HTMLDocument.<anonymous> (https://amberframework.org/dist/sidebar.bundle.js:2:47110)
    at j (https://amberframework.org/assets/js/core.min.js:2:29999)
    at k (https://amberframework.org/assets/js/core.min.js:2:30313) undefined
r.Deferred.exceptionHook @ core.min.js:2
core.min.js:2 Uncaught TypeError: Cannot read property 'href' of null
    at s (sidebar.bundle.js:2)
    at HTMLDocument.<anonymous> (sidebar.bundle.js:2)
    at j (core.min.js:2)
    at k (core.min.js:2)
```

This may have to do with relative paths, I have not looked into it yet.

**Comment by faustinoaq** [comment]
Latest changes have been deployed, Fixed now! :tada:
